defaults:
  - override hydra/launcher: submitit_slurm

seed: 0

target: 0

ot_coef: 0.01

num_iterations: 10000
batch_size: 128

hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}
    subdir: ${hydra.job.num}
  launcher:
    max_num_timeout: 100000
    timeout_min: 4319
    partition: learnfair
    mem_gb: 64
    cpus_per_task: 10
    gpus_per_node: 1